# Generated by Django 3.1.5 on 2021-01-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('type', models.CharField(choices=[('D', 'ยา'), ('M', 'เวชภัณฑ์')], max_length=1, verbose_name='Dispense type')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('med_sup_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Drug ID')),
                ('drug_id', models.CharField(max_length=24, null=True, verbose_name='Drug ID')),
                ('description', models.CharField(default='', max_length=255, verbose_name='Drug Description')),
                ('name', models.CharField(max_length=255, verbose_name='Drug name')),
                ('amount', models.IntegerField(verbose_name='Amount left')),
            ],
        ),
        migrations.CreateModel(
            name='Med_supply',
            fields=[
                ('med_sup_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Medical supply ID')),
                ('sup_id', models.CharField(max_length=24, null=True, verbose_name='Medical Supply ID')),
                ('name', models.CharField(max_length=255, verbose_name='Medical supply name')),
                ('description', models.CharField(default='', max_length=255, verbose_name='Medical Supply Description')),
                ('amount', models.IntegerField(verbose_name='Amount left')),
            ],
        ),
    ]
